---
title: "PERMANOVA"
author: "Yong-Xin Liu"
date: "2019/3/5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
rm(list=ls())
##导入需要的R包
library(vegan)
library(ggplot2)
library(ape)
library(dplyr)

# 构建函数. 提取CCA中主要结果
# Function1. get CCA main result
variability_table = function(cca){
  chi = c(cca$tot.chi, cca$CCA$tot.chi, cca$CA$tot.chi)
  variability_table = cbind(chi, chi/chi[1])
  colnames(variability_table) = c("inertia", "proportion")
  rownames(variability_table) = c("total", "constrained", "unconstrained")
  return(variability_table)
}

#读入数据
# ##读入mapping file
# grf.map <- read.table("design.txt",header = T,sep = "\t", row.names = 1)
# ##去掉Unifrac矩阵中没有的样品
# grf.map.temp <- grf.map[rownames(grf.map) != "NJ6NM73RsDB1R02",] 
# ##NJ6NM73RsDB1R02样品在weighted unifrac距离矩阵中没有，经过查看原始数据量，发现它的原始测序量不够。
# ##选取重复
# grf.map.temp <- grf.map.temp[grf.map.temp$replicate=="R01" |grf.map.temp$replicate=="R02" |grf.map.temp$replicate=="R03",]
# write.table(grf.map.temp, file="metadata.txt",append = F,quote = F,sep = '\t',row.names = T)

metadata <- read.table("metadata.txt",header = T,sep = "\t", row.names = 1)


##读入权重的和非全重的Unifrac距离矩阵
# wuf.grf.df <- read.table("/mnt/bai/zhiwen/16s/GRF_merge/result/beta/weighted_unifrac.txt", header = T,sep = "\t", row.names = 1)
# wuf.grf.df = wuf.grf.df[rownames(metadata), rownames(metadata)]
# write.table(wuf.grf.df, file="weighted_unifrac.txt",append = F,quote = F,sep = '\t',row.names = T)
dis <- read.table("weighted_unifrac.txt", header = T,sep = "\t", row.names = 1)
# uuf.grf.df <- read.table("/mnt/bai/zhiwen/16s/GRF_merge/result/beta/unweighted_unifrac.txt", header = T,sep = "\t", row.names = 1)
# counts_tab <- read.table("/mnt/bai/zhiwen/16s/GRF_merge/result/otutab_norm.txt", header = T, row.names = 1,sep="\t",comment.char = "")
# counts_tab = counts_tab[, rownames(metadata)]
# counts_tab = counts_tab[rowSums(counts_tab)>300,]
# write.table(counts_tab, file="otutab_norm.txt",append = F,quote = F,sep = '\t',row.names = T)
# otutab <- read.table("otutab_norm.txt", header = T,sep = "\t", row.names = 1)

#根据grf.map.temp筛选距离矩阵
# wuf.grf.df <- wuf.grf.df[match(row.names(grf.map.temp),row.names(wuf.grf.df)),match(row.names(grf.map.temp),colnames(wuf.grf.df))] 
# 计各因素占方差的解析解析率和是否显著
tem_adonis <- adonis (as.dist(dis) ~ compartment*condition*genotype*batch, data = metadata, by=NULL, parallel=8)
tem_adonis$aov.tab
```

计算compartment条件是否显著影响群落结果

```{r}
tem_adonis <- adonis (as.dist(dis) ~ compartment, data = metadata, by=NULL,parallel=3)
tem_adonis$aov.tab
```

计算genotype条件是否显著影响群落结果

```{r}
tem_adonis <- adonis (as.dist(dis) ~ genotype, data = metadata, by=NULL,parallel=3)
tem_adonis$aov.tab
```